package ar.edu.unlam.pb2.Enums;

public enum OpcionMenu {
	AGREGAR_PROPIEDAD,MODIFICAR_PROPIEDAD, AGREGAR_CLIENTE, OBTENER_LISTADO_POR_PRECIO,
	OBTENER_LISTADO_POR_UBICACION, BUSCAR_PROPIEDADES_POR_PRECIO, BUSCAR_PROPIEDADES_POR_UBICACION, REALIZAR_VENTA,
	REALIZAR_ALQUILER,REALIZAR_PERMUTACION,MOSTRAR_PROPIEDADES, MOSTRAR_CLIENTES;
}
//MOSTRAR_PROPIEDADES